// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfXtzcZ03VudWykVyfoRSNvM3TtPmDnhQ',
    appId: '1:716718206439:web:6f4f03e04cd027f12b2142',
    messagingSenderId: '716718206439',
    projectId: 'androidappsf333',
    authDomain: 'androidappsf333.firebaseapp.com',
    storageBucket: 'androidappsf333.firebasestorage.app',
    measurementId: 'G-XYVE3MR2W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHcn_1bXvn2NXeTAtBS3We09TonwCmDU',
    appId: '1:716718206439:android:2415019375f43e632b2142',
    messagingSenderId: '716718206439',
    projectId: 'androidappsf333',
    storageBucket: 'androidappsf333.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo_ZnouTgChfhPTTjAglpkbLoUC0n7YwM',
    appId: '1:716718206439:ios:49eb596fc67aa0a82b2142',
    messagingSenderId: '716718206439',
    projectId: 'androidappsf333',
    storageBucket: 'androidappsf333.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSf333',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo_ZnouTgChfhPTTjAglpkbLoUC0n7YwM',
    appId: '1:716718206439:ios:49eb596fc67aa0a82b2142',
    messagingSenderId: '716718206439',
    projectId: 'androidappsf333',
    storageBucket: 'androidappsf333.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSf333',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfXtzcZ03VudWykVyfoRSNvM3TtPmDnhQ',
    appId: '1:716718206439:web:ad94e172bca09e012b2142',
    messagingSenderId: '716718206439',
    projectId: 'androidappsf333',
    authDomain: 'androidappsf333.firebaseapp.com',
    storageBucket: 'androidappsf333.firebasestorage.app',
    measurementId: 'G-H85C2FME0J',
  );

}