// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsTB5AeJsOfMFS3yjVJMDVz0GQ2zpnFD0',
    appId: '1:285487496688:web:a7f659541474357b533135',
    messagingSenderId: '285487496688',
    projectId: 'tuenjai-prod',
    authDomain: 'tuenjai-prod.firebaseapp.com',
    storageBucket: 'tuenjai-prod.firebasestorage.app',
    measurementId: 'G-Q8ER7GDQJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABu1IrlDwPW_KxGqvlOZXmm_I5iGcM5Ww',
    appId: '1:285487496688:android:525ff7f019c0fe58533135',
    messagingSenderId: '285487496688',
    projectId: 'tuenjai-prod',
    storageBucket: 'tuenjai-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgkPF5rQ0EilN8yuaziPeOWHZWbLrGkGs',
    appId: '1:285487496688:ios:2c16f59d2e4b28af533135',
    messagingSenderId: '285487496688',
    projectId: 'tuenjai-prod',
    storageBucket: 'tuenjai-prod.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSf333',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgkPF5rQ0EilN8yuaziPeOWHZWbLrGkGs',
    appId: '1:285487496688:ios:2c16f59d2e4b28af533135',
    messagingSenderId: '285487496688',
    projectId: 'tuenjai-prod',
    storageBucket: 'tuenjai-prod.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSf333',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsTB5AeJsOfMFS3yjVJMDVz0GQ2zpnFD0',
    appId: '1:285487496688:web:abb36c103666a35e533135',
    messagingSenderId: '285487496688',
    projectId: 'tuenjai-prod',
    authDomain: 'tuenjai-prod.firebaseapp.com',
    storageBucket: 'tuenjai-prod.firebasestorage.app',
    measurementId: 'G-KSSTWG3V6J',
  );
}
